"""Runs the real simulator for every scenario the visualizer displays and
writes a downsampled JS data file. Not part of the library API — a
one-off generator invoked by demo.sh (and rerunnable any time the
visualizer needs fresh numbers)."""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import experiments as exp  # noqa: E402


def downsample(series, max_points=400):
    if len(series) <= max_points:
        return series
    stride = len(series) / max_points
    return [series[int(i * stride)] for i in range(max_points)]


def cwnd_xy(cwnd_series):
    return [[round(t, 4), round(c, 3)] for (t, c, _srtt) in downsample(cwnd_series)]


def main():
    data = {}

    # 1. single flow, all three algorithms, overlaid cwnd curves
    single = {}
    for algo in ("reno", "cubic", "bbr"):
        r = exp.run_single_flow(algo=algo, duration_s=20)
        single[algo] = {
            "cwnd": cwnd_xy(r["flows"][0]["cwnd_series"]),
            "utilization": r["flows"][0]["throughput_bps"] / 2_000_000,
            "drops": r["drop_count"],
        }
    data["single_flow"] = single

    # 2. same-RTT fairness convergence (two Reno flows)
    fr = exp.run_fairness_same_rtt(algo="reno", n_flows=2, duration_s=40)
    data["fairness"] = {
        "cwnd": [cwnd_xy(f["cwnd_series"]) for f in fr["flows"]],
        "fairness_series": [[round(t, 2), round(v, 4)] for (t, v) in fr["fairness_series"]],
        "delivered": [f["delivered_segments"] for f in fr["flows"]],
    }

    # 3. RTT unfairness: Reno vs CUBIC pooled ratio comparison
    reno_u = exp.run_rtt_unfairness(algo="reno", duration_s=60)
    cubic_u = exp.run_rtt_unfairness(algo="cubic", duration_s=60)
    data["rtt_unfairness"] = {
        "rtt_ratio": round(reno_u["rtt_ratio_long_over_short"], 2),
        "reno_pooled_ratio": round(reno_u["pooled_throughput_ratio_short_over_long"], 3),
        "cubic_pooled_ratio": round(cubic_u["pooled_throughput_ratio_short_over_long"], 3),
        "reno_cwnd": [cwnd_xy(f["cwnd_series"]) for f in reno_u["flows"]],
    }

    # 4. bufferbloat: drop-tail vs RED
    dt = exp.run_bufferbloat(algo="reno", use_red=False, duration_s=30)
    red = exp.run_bufferbloat(algo="reno", use_red=True, duration_s=30)

    def ping_rtt_series(result):
        ping = result["flows"][1]
        return [[round(t, 3), round(srtt * 1000, 2)] for (t, _c, srtt) in downsample(ping["cwnd_series"])
                if srtt is not None]

    def queue_series(result):
        return [[round(t, 3), q] for (t, q) in downsample(result["queue_samples"])]

    data["bufferbloat"] = {
        "base_rtt_ms": round(dt["base_rtt_s"] * 1000, 2),
        "drop_tail": {
            "ping_rtt_ms": ping_rtt_series(dt),
            "queue": queue_series(dt),
            "bloat_ratio": round(dt["bloat_ratio"], 2),
            "utilization": round(dt["bottleneck_utilization"], 3),
        },
        "red": {
            "ping_rtt_ms": ping_rtt_series(red),
            "queue": queue_series(red),
            "bloat_ratio": round(red["bloat_ratio"], 2),
            "utilization": round(red["bottleneck_utilization"], 3),
        },
    }

    # 5. BBR vs CUBIC queue occupancy
    bvl = exp.run_bbr_vs_loss_based(loss_algo="cubic", duration_s=30)
    data["bbr_vs_loss"] = {
        algo: {
            "queue": [[round(t, 3), q] for (t, q) in downsample(res["queue_samples"])],
            "utilization": round(res["utilization"], 3),
            "mean_queue": round(res["mean_queue_packets"], 2),
        }
        for algo, res in bvl["results"].items()
    }

    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "visualizer", "data.js")
    with open(out_path, "w") as f:
        f.write("// Generated by scripts/make_visualizer_data.py from real simulator runs.\n")
        f.write("const DEMO_DATA = ")
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")
    size_kb = os.path.getsize(out_path) / 1024
    print(f"Wrote {out_path} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
