"""A guided tour that exercises every feature and writes real artifacts."""

from __future__ import annotations

import os

from .metrics import Font
from .model import build_paragraph
from .hyphen import Hyphenator
from .linebreak import break_paragraph, greedy_break, evaluate_breaks, brute_force_break
from .render import (
    render_svg, render_ascii, ascii_paragraph,
    render_card, render_html_document,
)
from .verify import roundtrip_words, count_rivers
from .cli import SAMPLE


def _hr(title):
    print("\n" + title)
    print("-" * len(title))


def run_demo(outdir: str) -> int:
    os.makedirs(outdir, exist_ok=True)
    h = Hyphenator()

    print("=" * 64)
    print("  GALLEY — optimal typesetting demo")
    print("=" * 64)

    _hr("1. Liang hyphenation")
    for w in ["typesetting", "hyphenation", "algorithm", "representation",
              "beautiful", "knuth", "paragraph", "wonderful", "development"]:
        print(f"   {w:<16} {'-'.join(h.hyphenate(w))}")

    _hr("2. Knuth–Plass vs greedy (monospace column, width 46)")
    ap = ascii_paragraph(SAMPLE, hyphenate=h.hyphenate)
    kp_a = break_paragraph(ap.items, 46.0)
    print("   Optimal:")
    for ln in render_ascii(ap.items, kp_a):
        print("   |" + ln.ljust(46) + "|")
    ok, msg = roundtrip_words(ap.items, kp_a, ap.words)
    print(f"   round-trip integrity: {'OK' if ok else 'FAIL ' + msg}")

    _hr("3. Demerit comparison across measures (Times 11pt)")
    font = Font("times", 11)
    print(f"   {'measure':>8} {'KP dem':>10} {'greedy dem':>12} {'ratio':>7} "
          f"{'KP lines':>9} {'gr lines':>9}")
    for m in (216.0, 252.0, 288.0, 360.0):
        para = build_paragraph(SAMPLE, font, hyphenate=h.hyphenate)
        kp = break_paragraph(para.items, m)
        gr = greedy_break(para.items, m)
        grs = evaluate_breaks(para.items, gr.breaks, m)
        ratio = grs.total_demerits / max(kp.total_demerits, 1e-9)
        print(f"   {m:8.0f} {kp.total_demerits:10,.0f} {grs.total_demerits:12,.0f} "
              f"{ratio:6.1f}x {len(kp.lines):9d} {len(gr.lines):9d}")

    _hr("4. Differential verification vs brute-force optimum")
    import random
    rng = random.Random(20260618)
    words = ("the quick brown fox jumps over a lazy dog while typesetting "
             "beautiful paragraphs with optimal breaks and hyphenation").split()
    checked = mismatch = feasible = 0
    for _ in range(300):
        txt = " ".join(rng.choice(words) for _ in range(rng.randint(3, 8)))
        para = build_paragraph(txt, font, hyphenate=h.hyphenate)
        meas = float(rng.choice([90, 110, 140, 180]))
        kp = break_paragraph(para.items, meas, tolerance=200, escalate=False)
        bf_dem, _ = brute_force_break(para.items, meas, tolerance=200)
        checked += 1
        if bf_dem < 1e12:
            feasible += 1
            if not kp.feasible or abs(kp.total_demerits - bf_dem) > 1e-4:
                mismatch += 1
    print(f"   {checked} random paragraphs, {feasible} with a feasible breaking; "
          f"DP-vs-brute-force mismatches: {mismatch}")

    _hr("5. Writing visual artifacts")
    measure = 252.0
    para = build_paragraph(SAMPLE, font, hyphenate=h.hyphenate)
    kp = break_paragraph(para.items, measure)
    gr = greedy_break(para.items, measure)
    grs = evaluate_breaks(para.items, gr.breaks, measure)

    kp_svg_path = os.path.join(outdir, "knuth_plass.svg")
    gr_svg_path = os.path.join(outdir, "greedy.svg")
    _write(kp_svg_path, render_svg(para.items, kp, font, measure, heat=True,
                                   title="Knuth–Plass (optimal)"))
    _write(gr_svg_path, render_svg(para.items, gr, font, measure, heat=True,
                                   title="Greedy (first-fit)"))

    cards = [
        render_card("Knuth–Plass (optimal)",
                    f"{len(kp.lines)} lines · demerits {kp.total_demerits:,.0f}",
                    render_svg(para.items, kp, font, measure, heat=True),
                    _stats(kp)),
        render_card("Greedy (first-fit)",
                    f"{len(gr.lines)} lines · demerits {grs.total_demerits:,.0f}",
                    render_svg(para.items, gr, font, measure, heat=True),
                    _stats(grs)),
    ]
    cmp_path = os.path.join(outdir, "compare.html")
    _write(cmp_path, render_html_document(
        'Galley · <span class="accent">optimal</span> vs greedy line breaking',
        f"The same paragraph set in Times 11pt on a {measure:g}pt measure. "
        f"Greedy spends {grs.total_demerits / max(kp.total_demerits,1e-9):.0f}× "
        f"the demerits and uses {len(gr.lines)} lines to Knuth–Plass's "
        f"{len(kp.lines)}.",
        cards,
        footer="Generated by Galley — Knuth–Plass total-fit typesetting."))

    play_path = os.path.join(outdir, "playground.html")
    from .playground import build_playground
    _write(play_path, build_playground(SAMPLE, font_family="times", size=14))

    _hr("6. River detection (whitespace channels)")
    rivers = count_rivers(para.items, kp, font)
    print(f"   measure {measure:g}pt: {len(rivers)} river(s) >= 3 lines detected")
    for rv in rivers[:5]:
        print(f"     rows {rv['start_line']}–{rv['end_line']} "
              f"(len {rv['length']}) near x={rv['x']:.0f}pt")

    print("\nArtifacts written:")
    for p in (kp_svg_path, gr_svg_path, cmp_path, play_path):
        print(f"   {p}  ({os.path.getsize(p):,} bytes)")
    print("\nOpen compare.html and playground.html in a browser.")
    return 0


def _stats(breaking):
    lines = breaking.lines
    rs = [abs(l.ratio) for l in lines[:-1]] if len(lines) > 1 else [0.0]
    avg_r = sum(rs) / len(rs) if rs else 0.0
    overfull = sum(1 for l in lines if l.ratio < -1.0 - 1e-9)
    hyphens = sum(1 for l in lines if l.flagged)
    return [
        ("lines", str(len(lines))),
        ("demerits", f"{breaking.total_demerits:,.0f}" if breaking.feasible else "∞"),
        ("avg |r|", f"{avg_r:.2f}"),
        ("hyphens", str(hyphens)),
        ("overfull", str(overfull)),
    ]


def _write(path, content):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
