"""Generates a self-contained interactive HTML attention visualizer.

Runs a prompt through a trained checkpoint, grabs the real per-layer,
per-head attention weight matrices computed during that forward pass (they
are already cached inside each CausalSelfAttention module -- no extra
plumbing needed), and embeds them as JSON in a static HTML page with a
canvas-based heatmap and a layer/head picker.
"""
import argparse
import json
import os

import numpy as np

from train import load_checkpoint

HERE = os.path.dirname(__file__)

TEMPLATE = """<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Sprout — attention visualizer</title>
<style>
  :root { color-scheme: light dark; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    max-width: 900px; margin: 2rem auto; padding: 0 1rem;
    background: #0f1117; color: #e8e8ec;
  }
  h1 { font-size: 1.3rem; margin-bottom: 0.2rem; }
  .prompt { color: #9aa0ac; font-family: ui-monospace, monospace; margin-bottom: 1.2rem; }
  .controls { display: flex; gap: 1.5rem; margin-bottom: 1rem; flex-wrap: wrap; align-items: center; }
  .controls label { font-size: 0.85rem; color: #9aa0ac; }
  select, input[type=range] { accent-color: #6ea8fe; }
  #heatmap { border-radius: 8px; }
  #tokens { font-family: ui-monospace, monospace; font-size: 0.85rem; line-height: 1.6; margin-top: 1rem; }
  .tok { padding: 1px 2px; border-radius: 3px; cursor: default; }
  .legend { font-size: 0.75rem; color: #9aa0ac; margin-top: 0.4rem; }
  footer { margin-top: 2rem; font-size: 0.75rem; color: #666; }
</style>
</head>
<body>
<h1>Sprout attention visualizer</h1>
<div class="prompt">prompt: <span id="promptText"></span></div>
<div class="controls">
  <label>Layer <select id="layerSel"></select></label>
  <label>Head <select id="headSel"></select></label>
  <label>Query token
    <input type="range" id="querySlider" min="0" value="0" step="1">
    <span id="queryLabel"></span>
  </label>
</div>
<canvas id="heatmap" width="640" height="640"></canvas>
<div class="legend">Row = query position, column = key position. Bright = high attention weight.
Causal masking means a query can only attend to itself and earlier tokens (lower-left triangle).</div>
<div id="tokens"></div>
<footer>Generated by attention_viz.py from a real forward pass of a trained Sprout checkpoint — every value here is the model's actual computed attention weight, not illustrative.</footer>
<script>
const DATA = __DATA_JSON__;

const layerSel = document.getElementById('layerSel');
const headSel = document.getElementById('headSel');
const querySlider = document.getElementById('querySlider');
const queryLabel = document.getElementById('queryLabel');
const canvas = document.getElementById('heatmap');
const ctx = canvas.getContext('2d');

document.getElementById('promptText').textContent = JSON.stringify(DATA.tokens.join(''));

for (let l = 0; l < DATA.n_layer; l++) {
  const opt = document.createElement('option');
  opt.value = l; opt.textContent = 'Layer ' + l;
  layerSel.appendChild(opt);
}
for (let h = 0; h < DATA.n_head; h++) {
  const opt = document.createElement('option');
  opt.value = h; opt.textContent = 'Head ' + h;
  headSel.appendChild(opt);
}
querySlider.max = DATA.tokens.length - 1;

function renderTokens(queryIdx, weights) {
  const container = document.getElementById('tokens');
  container.innerHTML = '';
  DATA.tokens.forEach((t, i) => {
    const span = document.createElement('span');
    span.className = 'tok';
    const w = i <= queryIdx ? weights[i] : 0;
    const alpha = Math.min(1, w * 4);
    span.style.background = i === queryIdx
      ? 'rgba(110,168,254,0.9)'
      : `rgba(255,140,60,${alpha})`;
    span.textContent = t === '\\n' ? '↵\\n' : (t === ' ' ? '·' : t);
    container.appendChild(span);
  });
}

function draw() {
  const l = parseInt(layerSel.value), h = parseInt(headSel.value);
  const mat = DATA.attn[l][h]; // T x T
  const T = mat.length;
  const cell = canvas.width / T;
  ctx.fillStyle = '#0f1117';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  for (let i = 0; i < T; i++) {
    for (let j = 0; j < T; j++) {
      const w = mat[i][j];
      const v = Math.min(255, Math.round(w * 255 * 3));
      ctx.fillStyle = `rgb(${v}, ${Math.round(v*0.55)}, ${Math.round(255-v)})`;
      ctx.fillRect(j * cell, i * cell, cell + 0.5, cell + 0.5);
    }
  }
  const qi = parseInt(querySlider.value);
  queryLabel.textContent = JSON.stringify(DATA.tokens[qi]);
  renderTokens(qi, mat[qi]);
}

[layerSel, headSel, querySlider].forEach(el => el.addEventListener('input', draw));
draw();
</script>
</body>
</html>
"""


def build_html(model, tok, prompt, out_path):
    ids = tok.encode(prompt)
    if not ids:
        raise ValueError("prompt encodes to zero tokens")
    ids = ids[-model.block_size :]
    x = np.array([ids])
    model.forward(x)  # populates each block's attention cache

    tokens = [tok.decode([i]) for i in ids]
    attn_all_layers = []
    for blk in model.blocks:
        attn = blk.attn._cache[3][0]  # (H, T, T)
        attn_all_layers.append(attn.tolist())

    data = {
        "tokens": tokens,
        "n_layer": len(model.blocks),
        "n_head": model.blocks[0].attn.n_heads,
        "attn": attn_all_layers,
    }
    html = TEMPLATE.replace("__DATA_JSON__", json.dumps(data))
    with open(out_path, "w") as f:
        f.write(html)
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", default=os.path.join(HERE, "checkpoints", "sprout.pkl"))
    ap.add_argument("--prompt", default="the fox and the otter argued about")
    ap.add_argument("--out", default=os.path.join(HERE, "attention_viz.html"))
    args = ap.parse_args()

    try:
        model, tok, data = load_checkpoint(args.checkpoint)
    except FileNotFoundError:
        raise SystemExit(f"No checkpoint found at {args.checkpoint}. Run train.py first.")

    path = build_html(model, tok, args.prompt, args.out)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
