"""Generates MODEL_CARD.md from a trained checkpoint: an honest, auto-produced
report of what was actually trained -- size, data, loss curve, perplexity,
and real sample generations -- rather than hand-written marketing copy.
"""
import argparse
import math
import os

import numpy as np

from generate import sample
from train import load_checkpoint

HERE = os.path.dirname(__file__)
CORPUS_PATH = os.path.join(HERE, "data", "corpus.txt")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", default=os.path.join(HERE, "checkpoints", "sprout.pkl"))
    ap.add_argument("--out", default=os.path.join(os.path.dirname(HERE), "MODEL_CARD.md"))
    args = ap.parse_args()

    model, tok, data = load_checkpoint(args.checkpoint)
    history = data["history"]
    config = data["config"]

    with open(CORPUS_PATH) as f:
        corpus_text = f.read()

    final_train = history["train_loss"][-1]
    final_val = history["val_loss"][-1]
    ppl_train = math.exp(final_train)
    ppl_val = math.exp(final_val)

    rng = np.random.default_rng(42)
    prompts = ["the fox", "a heron", '"I saw a', "Day at"]
    samples = []
    for p in prompts:
        text = sample(model, tok, prompt=p, max_new_tokens=80, temperature=0.8, top_k=40, rng=rng)
        samples.append((p, text))

    lines = []
    lines.append("# Sprout — model card")
    lines.append("")
    lines.append("Auto-generated by `model_card.py` from the actual trained checkpoint. "
                  "Every number and sample below came from running the real model, not from "
                  "hand-written copy.")
    lines.append("")
    lines.append("## Architecture")
    lines.append("")
    lines.append(f"- Type: GPT-style decoder-only transformer, hand-written forward/backward (see `nn.py`)")
    lines.append(f"- Layers: {config['n_layer']}")
    lines.append(f"- Attention heads: {config['n_head']}")
    lines.append(f"- Embedding dim: {config['n_embd']}")
    lines.append(f"- Context length (block size): {config['block_size']}")
    lines.append(f"- Vocabulary size (BPE): {config['vocab_size']}")
    lines.append(f"- Total parameters: {model.num_params():,}")
    lines.append("")
    lines.append("## Data")
    lines.append("")
    lines.append(f"- Corpus: `data/corpus.txt`, {len(corpus_text):,} characters, "
                  f"entirely original text generated for this project (see `data/make_corpus.py`)")
    lines.append("- Split: 90% train / 10% validation, contiguous")
    lines.append("")
    lines.append("## Training")
    lines.append("")
    lines.append(f"- Steps: {data['step']:,}")
    lines.append(f"- Optimizer: Adam (from scratch, `optim.py`), gradient clipped to norm 1.0")
    lines.append(f"- Final train loss: {final_train:.4f}  (perplexity {ppl_train:.2f})")
    lines.append(f"- Final val loss:   {final_val:.4f}  (perplexity {ppl_val:.2f})")
    lines.append("")
    lines.append("### Loss curve")
    lines.append("")
    lines.append("| step | train_loss | val_loss |")
    lines.append("|---:|---:|---:|")
    for s, tl, vl in zip(history["step"], history["train_loss"], history["val_loss"]):
        lines.append(f"| {s} | {tl:.3f} | {vl:.3f} |")
    lines.append("")
    lines.append("## Sample generations (temperature=0.8, top_k=40, this checkpoint)")
    lines.append("")
    for p, text in samples:
        lines.append(f"**Prompt:** `{p!r}`")
        lines.append("")
        lines.append("```")
        lines.append(text)
        lines.append("```")
        lines.append("")
    lines.append("## Honest assessment")
    lines.append("")
    lines.append(
        f"This is a ~{model.num_params()/1e6:.1f}M-parameter model trained for {data['step']:,} steps "
        f"on {len(corpus_text)/1000:.0f}KB of text. It reliably produces English word shapes, "
        "spacing, capitalization after sentence-ending punctuation, and quoted-dialogue "
        "punctuation because those patterns are extremely frequent and low-entropy in the "
        "corpus. It does **not** reliably produce globally coherent narrative -- that needs "
        "far more parameters and far more data than a CPU-trained toy model has access to. "
        "The loss curve and perplexity above are the honest measure of where it landed, not "
        "the cherry-picked samples."
    )
    lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
