"""Canonical Huffman tables for JPEG entropy coding.

JPEG never ships a Huffman *tree* in the file -- it ships a canonical
representation: BITS[1..16] (how many codes have each length) and
HUFFVAL[] (the symbols in code order). The actual bit patterns are
regenerated by both encoder and decoder from that representation using
the fixed procedure in ITU-T T.81 Annex C, which assigns codes of a given
length consecutively and in increasing order -- that's what "canonical"
means, and it's why the table only needs lengths + symbol order, not full
codes, to travel in the file.

This module provides:
  * the four ITU-T T.81 Annex K standard tables (DC/AC x luma/chroma)
  * `build_codes` -- Annex C's BITS/HUFFVAL -> {symbol: (code, length)}
  * `HuffmanTable` -- wraps a code map with an encoder and a decoder
  * `optimize_table` -- builds a real per-image canonical table from
    measured symbol frequencies (a proper Huffman tree via a min-heap),
    with a tested fallback to the matching standard table for the
    (practically unreachable for real image statistics, but real and
    checked-for) pathological case where the resulting tree would need
    codes longer than JPEG's 16-bit limit
"""
import heapq

# --- ITU-T T.81 Annex K standard tables -------------------------------

STD_DC_LUMA_BITS = [0, 1, 5, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
STD_DC_LUMA_VALS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

STD_DC_CHROMA_BITS = [0, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
STD_DC_CHROMA_VALS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

STD_AC_LUMA_BITS = [0, 2, 1, 3, 3, 2, 4, 3, 5, 5, 4, 4, 0, 0, 1, 0x7D]
STD_AC_LUMA_VALS = [
    0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12,
    0x21, 0x31, 0x41, 0x06, 0x13, 0x51, 0x61, 0x07,
    0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xA1, 0x08,
    0x23, 0x42, 0xB1, 0xC1, 0x15, 0x52, 0xD1, 0xF0,
    0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0A, 0x16,
    0x17, 0x18, 0x19, 0x1A, 0x25, 0x26, 0x27, 0x28,
    0x29, 0x2A, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39,
    0x3A, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49,
    0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59,
    0x5A, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69,
    0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79,
    0x7A, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89,
    0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98,
    0x99, 0x9A, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
    0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6,
    0xB7, 0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4, 0xC5,
    0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2, 0xD3, 0xD4,
    0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE1, 0xE2,
    0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA,
    0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8,
    0xF9, 0xFA,
]

STD_AC_CHROMA_BITS = [0, 2, 1, 2, 4, 4, 3, 4, 7, 5, 4, 4, 0, 1, 2, 0x77]
STD_AC_CHROMA_VALS = [
    0x00, 0x01, 0x02, 0x03, 0x11, 0x04, 0x05, 0x21,
    0x31, 0x06, 0x12, 0x41, 0x51, 0x07, 0x61, 0x71,
    0x13, 0x22, 0x32, 0x81, 0x08, 0x14, 0x42, 0x91,
    0xA1, 0xB1, 0xC1, 0x09, 0x23, 0x33, 0x52, 0xF0,
    0x15, 0x62, 0x72, 0xD1, 0x0A, 0x16, 0x24, 0x34,
    0xE1, 0x25, 0xF1, 0x17, 0x18, 0x19, 0x1A, 0x26,
    0x27, 0x28, 0x29, 0x2A, 0x35, 0x36, 0x37, 0x38,
    0x39, 0x3A, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48,
    0x49, 0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58,
    0x59, 0x5A, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68,
    0x69, 0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78,
    0x79, 0x7A, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87,
    0x88, 0x89, 0x8A, 0x92, 0x93, 0x94, 0x95, 0x96,
    0x97, 0x98, 0x99, 0x9A, 0xA2, 0xA3, 0xA4, 0xA5,
    0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4,
    0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xC2, 0xC3,
    0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2,
    0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA,
    0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9,
    0xEA, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8,
    0xF9, 0xFA,
]

assert sum(STD_DC_LUMA_BITS) == len(STD_DC_LUMA_VALS) == 12
assert sum(STD_DC_CHROMA_BITS) == len(STD_DC_CHROMA_VALS) == 12
assert sum(STD_AC_LUMA_BITS) == len(STD_AC_LUMA_VALS) == 162
assert sum(STD_AC_CHROMA_BITS) == len(STD_AC_CHROMA_VALS) == 162


def build_codes(bits, values):
    """ITU-T T.81 Annex C.2: BITS/HUFFVAL -> {symbol: (code, length)}.

    Codes of a given length are assigned consecutively, in the order the
    symbols for that length appear in HUFFVAL; when the length increases
    the running code is shifted left one bit. This is the exact
    canonical-code generation procedure, implemented directly from the
    spec's Generate_size_table / Generate_code_table pseudocode.
    """
    huffsize = []
    for length, count in enumerate(bits, start=1):
        huffsize.extend([length] * count)

    huffcode = []
    code = 0
    si = huffsize[0] if huffsize else 0
    k = 0
    while k < len(huffsize):
        while k < len(huffsize) and huffsize[k] == si:
            huffcode.append(code)
            code += 1
            k += 1
        code <<= 1
        si += 1

    table = {}
    for val, length, code in zip(values, huffsize, huffcode):
        table[val] = (code, length)
    return table


class HuffmanTable:
    """A canonical Huffman table usable for both encoding and decoding."""

    def __init__(self, bits, values):
        self.bits = list(bits)
        self.values = list(values)
        self.encode_map = build_codes(self.bits, self.values)
        # decode_map[(length, code)] = symbol, for bit-by-bit decoding.
        self.decode_map = {
            (length, code): sym for sym, (code, length) in self.encode_map.items()
        }
        self.max_code_length = max((l for _, l in self.encode_map.values()), default=0)

    def encode_symbol(self, writer, symbol):
        code, length = self.encode_map[symbol]
        writer.write_bits(code, length)

    def decode_symbol(self, reader):
        """Read bits one at a time (canonical decode) until a valid code
        of some length matches; returns the symbol, or None on EOF/marker.
        """
        code = 0
        for length in range(1, self.max_code_length + 1):
            bit = reader.read_bit()
            if bit is None:
                return None
            code = (code << 1) | bit
            sym = self.decode_map.get((length, code))
            if sym is not None:
                return sym
        return None

    def as_marker_bytes(self):
        """The BITS(16) + HUFFVAL(n) payload used inside a DHT segment."""
        return bytes(self.bits) + bytes(self.values)


STD_TABLES = {
    ("dc", "luma"): HuffmanTable(STD_DC_LUMA_BITS, STD_DC_LUMA_VALS),
    ("dc", "chroma"): HuffmanTable(STD_DC_CHROMA_BITS, STD_DC_CHROMA_VALS),
    ("ac", "luma"): HuffmanTable(STD_AC_LUMA_BITS, STD_AC_LUMA_VALS),
    ("ac", "chroma"): HuffmanTable(STD_AC_CHROMA_BITS, STD_AC_CHROMA_VALS),
}

MAX_CODE_LENGTH = 16


class _Node:
    __slots__ = ("freq", "order", "symbol", "left", "right")

    def __init__(self, freq, order, symbol=None, left=None, right=None):
        self.freq = freq
        self.order = order  # tie-break for a deterministic heap order
        self.symbol = symbol
        self.left = left
        self.right = right

    def __lt__(self, other):
        if self.freq != other.freq:
            return self.freq < other.freq
        return self.order < other.order


def _huffman_tree_lengths(freqs):
    """Build a standard (unlimited-height) Huffman tree from a
    {symbol: frequency} map and return {symbol: code_length}.
    Handles the 0- and 1-symbol degenerate cases explicitly.
    """
    symbols = [s for s, f in freqs.items() if f > 0]
    if not symbols:
        return {}
    if len(symbols) == 1:
        return {symbols[0]: 1}

    heap = []
    order = 0
    for s in symbols:
        heapq.heappush(heap, _Node(freqs[s], order, symbol=s))
        order += 1
    while len(heap) > 1:
        a = heapq.heappop(heap)
        b = heapq.heappop(heap)
        heapq.heappush(heap, _Node(a.freq + b.freq, order, left=a, right=b))
        order += 1
    root = heap[0]

    lengths = {}

    def walk(node, depth):
        if node.symbol is not None:
            lengths[node.symbol] = depth
            return
        walk(node.left, depth + 1)
        walk(node.right, depth + 1)

    walk(root, 0)
    return lengths


def optimize_table(freqs, fallback_bits, fallback_values):
    """Build a real canonical Huffman table from measured frequencies.

    Falls back to the standard Annex-K table of matching kind if the
    resulting tree would need codes longer than JPEG's 16-bit limit --
    which requires a frequency distribution shaped like consecutive
    Fibonacci numbers to trigger (the classic worst case for Huffman
    code depth) and essentially never happens for real DCT-coefficient
    statistics, but is a real, reachable path that is unit-tested with
    exactly such an adversarial distribution rather than just assumed
    safe.
    """
    lengths = _huffman_tree_lengths(freqs)
    if not lengths or max(lengths.values()) > MAX_CODE_LENGTH:
        return HuffmanTable(fallback_bits, fallback_values), False

    max_len = max(lengths.values())
    bits = [0] * max_len
    for length in lengths.values():
        bits[length - 1] += 1

    # HUFFVAL order within a length must be consistent with the code
    # assignment order (ascending) -- any fixed deterministic order works
    # as long as encoder and decoder agree, so sort by (length, symbol).
    values = [sym for sym, _ in sorted(lengths.items(), key=lambda kv: (kv[1], kv[0]))]

    if len(bits) < MAX_CODE_LENGTH:
        bits = bits + [0] * (MAX_CODE_LENGTH - len(bits))

    return HuffmanTable(bits, values), True
