// Package report renders a self-contained HTML report of a solve.
package report

import (
	"fmt"
	"html"
	"math"
	"math/big"
	"strings"
	"time"

	"dantzig/internal/bb"
	"dantzig/internal/model"
	"dantzig/internal/sens"
)

const maxTreeNodes = 700

func esc(s string) string { return html.EscapeString(s) }

func num(r *big.Rat) string {
	if r == nil {
		return "-"
	}
	if r.IsInt() && len(r.Num().String()) <= 15 {
		return r.Num().String()
	}
	if s := r.RatString(); len(s) <= 18 {
		return s + " (≈ " + model.DecStr(r) + ")"
	}
	return "≈ " + model.DecStr(r)
}

func rng(r sens.Range) string {
	lo, hi := "−∞", "+∞"
	if r.Lo != nil {
		lo = model.DecStr(r.Lo)
	}
	if r.Hi != nil {
		hi = model.DecStr(r.Hi)
	}
	return "[" + lo + ", " + hi + "]"
}

// Build returns the HTML document. name labels the model; sr may be nil.
func Build(name string, m *model.Model, res *bb.Result, sr *sens.Report) string {
	var b strings.Builder
	nint := 0
	for _, v := range m.Vars {
		if v.Int {
			nint++
		}
	}
	kind := "Linear program"
	if nint > 0 {
		kind = "Mixed-integer program"
	}
	b.WriteString(head)
	status := strings.ToUpper(string(res.Status))
	cls := "ok"
	if !res.Certified {
		cls = "warn"
	}
	cert := "exact certificate verified"
	if !res.Certified {
		cert = "not fully certified"
	}
	fmt.Fprintf(&b, `<header><div class="wrap"><p class="eyebrow">Dantzig · %s</p><h1>%s</h1>
<p class="sub">%d variables (%d integer) · %d constraints · %s</p>
<p><span class="badge %s"><span class="dot"></span>%s</span> <span class="badge ghost">%s</span></p></div></header><main class="wrap">`,
		kind, esc(name), len(m.Vars), nint, len(m.Rows), map[bool]string{true: "maximise", false: "minimise"}[m.Maximize], cls, status, cert)

	// KPI tiles
	b.WriteString(`<section class="tiles">`)
	if res.Obj != nil {
		tile(&b, "Objective", num(res.Obj))
	}
	if res.Bound != nil && res.Status == bb.Limit {
		tile(&b, "Proven bound", num(res.Bound))
	}
	if nint > 0 {
		tile(&b, "B&B nodes", fmt.Sprint(res.Nodes))
	}
	tile(&b, "Simplex iterations", fmt.Sprint(res.LPIters))
	tile(&b, "Time", res.Elapsed.Round(10*time.Microsecond).String())
	if res.RootLP != nil && nint > 0 {
		tile(&b, "Root LP bound", fmt.Sprintf("%.6g", *res.RootLP))
	}
	b.WriteString(`</section>`)
	if res.Note != "" {
		fmt.Fprintf(&b, `<p class="note">%s</p>`, esc(res.Note))
	}

	if len(res.Trace) > 1 {
		b.WriteString(`<section><h2>Search convergence</h2><p class="muted">Incumbent (best solution found) and proven bound versus nodes explored. The gap closing to zero is the proof of optimality.</p>`)
		b.WriteString(convergence(res.Trace))
		b.WriteString(`</section>`)
	}
	if res.Proof != nil && len(res.Proof.Nodes) > 1 {
		b.WriteString(`<section><h2>Proof tree</h2><p class="muted">Every leaf carries an exact rational certificate; a separate checker re-verifies them all.</p>`)
		b.WriteString(treeSVG(res.Proof))
		b.WriteString(`</section>`)
	}
	if res.X != nil {
		b.WriteString(`<section><h2>Solution</h2>`)
		b.WriteString(solution(m, res))
		b.WriteString(`</section>`)
	}
	if sr != nil {
		b.WriteString(`<section><h2>Sensitivity analysis</h2><p class="muted">Exact, from the final basis. Ranges apply to one change at a time.</p>`)
		b.WriteString(sensTables(sr))
		b.WriteString(`</section>`)
	}
	if res.Proof != nil {
		leaves, bound, fark, open := 0, 0, 0, 0
		for _, n := range res.Proof.Nodes {
			if n.Var != nil {
				continue
			}
			leaves++
			switch n.Leaf {
			case "bound":
				bound++
			case "farkas", "gcd":
				fark++
			case "open", "uncertified":
				open++
			}
		}
		fmt.Fprintf(&b, `<section><h2>Certificate</h2><dl class="kv"><dt>Model SHA-256</dt><dd><code>%s</code></dd><dt>Proof tree</dt><dd>%d leaves: %d bound, %d infeasibility, %d open/uncertified</dd><dt>Verify independently</dt><dd><code>dantzig solve model.lp --proof p.json &amp;&amp; dantzig check model.lp p.json</code></dd></dl></section>`,
			res.Proof.ModelHash, leaves, bound, fark, open)
	}
	fmt.Fprintf(&b, `<section><details><summary>Model (canonical form)</summary><pre>%s</pre></details></section>`, esc(model.Format(m)))
	b.WriteString(`</main><footer class="wrap muted">Generated by Dantzig · all numbers exact unless marked ≈</footer></body></html>`)
	return b.String()
}

func tile(b *strings.Builder, k, v string) {
	if i := strings.Index(v, " (≈ "); i > 0 {
		v = "≈ " + strings.TrimSuffix(v[i+4:], ")") // tiles show the decimal only
	}
	fmt.Fprintf(b, `<div class="tile"><div class="k">%s</div><div class="v">%s</div></div>`, esc(k), esc(v))
}

func solution(m *model.Model, res *bb.Result) string {
	var b strings.Builder
	maxAbs := 0.0
	for _, x := range res.X {
		if f := math.Abs(model.Float(x)); f > maxAbs {
			maxAbs = f
		}
	}
	b.WriteString(`<table><thead><tr><th>Variable</th><th class="r">Value</th><th></th></tr></thead><tbody>`)
	shown := 0
	for j, v := range m.Vars {
		if res.X[j].Sign() == 0 {
			continue
		}
		if shown >= 300 {
			b.WriteString(`<tr><td colspan="3" class="muted">… more nonzero variables omitted</td></tr>`)
			break
		}
		shown++
		w := 0.0
		if maxAbs > 0 {
			w = 100 * math.Abs(model.Float(res.X[j])) / maxAbs
		}
		fmt.Fprintf(&b, `<tr><td>%s</td><td class="r mono">%s</td><td class="bar"><span style="width:%.1f%%"></span></td></tr>`, esc(v.Name), esc(num(res.X[j])), w)
	}
	if shown == 0 {
		b.WriteString(`<tr><td colspan="3" class="muted">all variables are zero</td></tr>`)
	}
	b.WriteString(`</tbody></table>`)
	return b.String()
}

func sensTables(sr *sens.Report) string {
	var b strings.Builder
	b.WriteString(`<div class="scroll"><table><thead><tr><th>Variable</th><th class="r">Value</th><th>Status</th><th class="r">Cost</th><th class="r">Reduced cost</th><th>Cost range</th></tr></thead><tbody>`)
	for _, v := range sr.Vars {
		fmt.Fprintf(&b, `<tr><td>%s</td><td class="r mono">%s</td><td>%s</td><td class="r mono">%s</td><td class="r mono">%s</td><td class="mono">%s</td></tr>`,
			esc(v.Name), esc(num(v.Value)), v.Status, esc(model.DecStr(v.Cost)), esc(model.DecStr(v.ReducedCost)), esc(rng(v.CostRange)))
	}
	b.WriteString(`</tbody></table></div><div class="scroll"><table><thead><tr><th>Constraint</th><th class="r">Activity</th><th class="r">Slack</th><th>Binding</th><th class="r">Shadow price</th><th>Limit range</th></tr></thead><tbody>`)
	for _, r := range sr.Rows {
		bd := r.Binding
		if bd == "" {
			bd = "–"
		}
		fmt.Fprintf(&b, `<tr><td>%s</td><td class="r mono">%s</td><td class="r mono">%s</td><td>%s</td><td class="r mono">%s</td><td class="mono">%s</td></tr>`,
			esc(r.Name), esc(model.DecStr(r.Activity)), esc(model.DecStr(r.Slack)), bd, esc(model.DecStr(r.Dual)), esc(rng(r.LimitRange)))
	}
	b.WriteString(`</tbody></table></div>`)
	return b.String()
}

// convergence draws incumbent and bound against node count.
func convergence(tr []bb.TracePoint) string {
	const W, H, L, R, T, B = 760.0, 280.0, 64.0, 16.0, 16.0, 36.0
	maxN := 1
	lo, hi := math.Inf(1), math.Inf(-1)
	for _, p := range tr {
		if p.Node > maxN {
			maxN = p.Node
		}
		for _, v := range []*float64{p.Incumbent, p.Bound} {
			if v != nil {
				lo, hi = math.Min(lo, *v), math.Max(hi, *v)
			}
		}
	}
	if math.IsInf(lo, 0) {
		return `<p class="muted">no incumbent or bound was recorded</p>`
	}
	if hi-lo < 1e-9 {
		lo, hi = lo-1, hi+1
	}
	pad := (hi - lo) * 0.08
	lo, hi = lo-pad, hi+pad
	x := func(n int) float64 { return L + (W-L-R)*float64(n)/float64(maxN) }
	y := func(v float64) float64 { return T + (H-T-B)*(1-(v-lo)/(hi-lo)) }
	var b strings.Builder
	fmt.Fprintf(&b, `<figure><svg viewBox="0 0 %g %g" role="img" aria-label="Incumbent and bound versus nodes explored" class="chart">`, W, H)
	for i := 0; i <= 4; i++ {
		v := lo + (hi-lo)*float64(i)/4
		fmt.Fprintf(&b, `<line class="grid" x1="%g" x2="%g" y1="%.1f" y2="%.1f"/><text class="axis" x="%g" y="%.1f" text-anchor="end">%s</text>`, L, W-R, y(v), y(v), L-8, y(v)+4, fmtNum(v))
	}
	for i := 0; i <= 4; i++ {
		n := int(float64(maxN) * float64(i) / 4)
		fmt.Fprintf(&b, `<text class="axis" x="%.1f" y="%g" text-anchor="middle">%d</text>`, x(n), H-14, n)
	}
	series := func(get func(bb.TracePoint) *float64, cls string) {
		var pts []string
		for _, p := range tr {
			if v := get(p); v != nil {
				pts = append(pts, fmt.Sprintf("%.1f,%.1f", x(p.Node), y(*v)))
			}
		}
		if len(pts) > 0 {
			fmt.Fprintf(&b, `<polyline class="line %s" points="%s"/>`, cls, strings.Join(pts, " "))
			last := strings.Split(pts[len(pts)-1], ",")
			fmt.Fprintf(&b, `<circle class="pt %s" cx="%s" cy="%s" r="4.5"/>`, cls, last[0], last[1])
		}
	}
	series(func(p bb.TracePoint) *float64 { return p.Bound }, "bound")
	series(func(p bb.TracePoint) *float64 { return p.Incumbent }, "inc")
	b.WriteString(`</svg><figcaption><span class="key inc"></span> incumbent &nbsp; <span class="key bound"></span> proven bound &nbsp; <span class="muted">x: nodes explored</span></figcaption></figure>`)
	return b.String()
}

func fmtNum(v float64) string {
	if math.Abs(v) >= 1e6 || (v != 0 && math.Abs(v) < 1e-3) {
		return fmt.Sprintf("%.3g", v)
	}
	return fmt.Sprintf("%.4g", v)
}

// treeSVG lays out the proof tree: leaves evenly spaced, parents centred.
func treeSVG(p *bb.Proof) string {
	nodes := p.Nodes
	n := len(nodes)
	depth := make([]int, n)
	hidden := make([]bool, n)
	// depth limit so very large trees stay legible
	limit := 1 << 30
	for limit > 0 {
		count := 0
		for i := range nodes {
			if nodes[i].Var != nil {
				depth[nodes[i].Down], depth[nodes[i].Up] = depth[i]+1, depth[i]+1
			}
		}
		maxd := 0
		for _, d := range depth {
			if d > maxd {
				maxd = d
			}
		}
		for d := 0; d <= maxd; d++ {
			c := 0
			for i := range depth {
				if depth[i] <= d {
					c++
				}
			}
			if c <= maxTreeNodes {
				count = d
			}
		}
		limit = count
		break
	}
	// visible = depth <= limit; a branch node at the limit becomes a collapsed stub
	pos := make([]float64, n)
	next := 0.0
	var order []int
	stack := []int{0}
	// iterative post-order
	type fr struct {
		i    int
		done bool
	}
	st := []fr{{0, false}}
	_ = stack
	for len(st) > 0 {
		f := st[len(st)-1]
		st = st[:len(st)-1]
		nd := nodes[f.i]
		collapsed := nd.Var != nil && depth[f.i] >= limit
		if nd.Var == nil || collapsed {
			pos[f.i] = next
			next++
			order = append(order, f.i)
			if collapsed {
				hidden[f.i] = true
			}
			continue
		}
		if !f.done {
			st = append(st, fr{f.i, true}, fr{nd.Up, false}, fr{nd.Down, false})
		} else {
			pos[f.i] = (pos[nd.Down] + pos[nd.Up]) / 2
			order = append(order, f.i)
		}
	}
	maxd := 0
	for _, i := range order {
		if depth[i] > maxd {
			maxd = depth[i]
		}
	}
	cw, rh := 26.0, 44.0
	W := math.Max(next*cw+40, 320)
	H := float64(maxd+1)*rh + 40
	var b strings.Builder
	fmt.Fprintf(&b, `<div class="scroll"><svg class="tree" viewBox="0 0 %.0f %.0f" width="%.0f" height="%.0f" role="img" aria-label="Branch and bound proof tree">`, W, H, W, H)
	px := func(i int) float64 { return 20 + pos[i]*cw + cw/2 }
	py := func(i int) float64 { return 24 + float64(depth[i])*rh }
	for _, i := range order {
		nd := nodes[i]
		if nd.Var != nil && !hidden[i] {
			for k, c := range []int{nd.Down, nd.Up} {
				lbl := "≤"
				if k == 1 {
					lbl = "≥"
				}
				_ = lbl
				fmt.Fprintf(&b, `<line class="edge" x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f"/>`, px(i), py(i), px(c), py(c))
			}
		}
	}
	for _, i := range order {
		nd := nodes[i]
		x, y := px(i), py(i)
		title := ""
		switch {
		case hidden[i]:
			fmt.Fprintf(&b, `<g><title>subtree collapsed (tree has %d nodes in total)</title><rect class="n stub" x="%.1f" y="%.1f" width="14" height="14" rx="3"/><text class="plus" x="%.1f" y="%.1f" text-anchor="middle">+</text></g>`, n, x-7, y-7, x, y+4)
			continue
		case nd.Var != nil:
			title = fmt.Sprintf("branch on variable #%d at %s", *nd.Var, nd.Split)
			fmt.Fprintf(&b, `<g><title>%s</title><circle class="n br" cx="%.1f" cy="%.1f" r="5"/></g>`, esc(title), x, y)
		case nd.Leaf == "bound" && nd.Inc:
			fmt.Fprintf(&b, `<g><title>incumbent leaf%s</title><polygon class="n inc" points="%.1f,%.1f %.1f,%.1f %.1f,%.1f %.1f,%.1f"/></g>`, lpTitle(nd), x, y-8, x+8, y, x, y+8, x-8, y)
		case nd.Leaf == "bound":
			fmt.Fprintf(&b, `<g><title>pruned by bound%s</title><rect class="n bd" x="%.1f" y="%.1f" width="12" height="12" rx="2"/></g>`, lpTitle(nd), x-6, y-6)
		case nd.Leaf == "farkas" || nd.Leaf == "gcd":
			fmt.Fprintf(&b, `<g><title>infeasible (%s certificate)</title><polygon class="n fk" points="%.1f,%.1f %.1f,%.1f %.1f,%.1f"/></g>`, nd.Leaf, x, y-7, x+7, y+6, x-7, y+6)
		default:
			fmt.Fprintf(&b, `<g><title>%s leaf (search stopped)</title><circle class="n op" cx="%.1f" cy="%.1f" r="6"/></g>`, esc(nd.Leaf), x, y)
		}
	}
	b.WriteString(`</svg></div><p class="legend"><span><svg width="14" height="14"><circle class="n br" cx="7" cy="7" r="5"/></svg> branch</span><span><svg width="14" height="14"><rect class="n bd" x="1" y="1" width="12" height="12" rx="2"/></svg> pruned by bound</span><span><svg width="14" height="14"><polygon class="n fk" points="7,1 14,13 0,13"/></svg> infeasible</span><span><svg width="16" height="16"><polygon class="n inc" points="8,0 16,8 8,16 0,8"/></svg> incumbent</span><span><svg width="14" height="14"><circle class="n op" cx="7" cy="7" r="6"/></svg> open</span></p>`)
	if limit < maxd+1000 && anyHidden(hidden) {
		fmt.Fprintf(&b, `<p class="muted">Deep part of a %d-node tree collapsed (+); the full tree is in the proof file.</p>`, n)
	}
	return b.String()
}

func anyHidden(h []bool) bool {
	for _, v := range h {
		if v {
			return true
		}
	}
	return false
}

func lpTitle(n bb.FlatNode) string {
	if n.LP != nil {
		return fmt.Sprintf(" (LP %.6g)", *n.LP)
	}
	return ""
}

const head = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dantzig report</title><style>
:root{--bg:#f7f7f4;--surface:#fff;--ink:#1d1f24;--ink2:#4a4f5a;--muted:#737a87;--line:#e3e4df;--accent:#2a6fdb;--good:#1a9e6b;--warn:#d98a1c;--bad:#c23b4f;--inc:#1a9e6b;--bound:#2a6fdb}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#15161a;--surface:#1d1f25;--ink:#ececec;--ink2:#b4b8c2;--muted:#868c99;--line:#2d3038;--accent:#6aa5f5;--good:#3fcf94;--warn:#f0b04a;--bad:#f0788a;--inc:#3fcf94;--bound:#6aa5f5}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}
.wrap{max-width:980px;margin:0 auto;padding:0 16px}header{padding:36px 0 8px}main{padding-bottom:40px}
.eyebrow{margin:0;font-size:13px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}h1{margin:.1em 0 .1em;font-size:clamp(26px,5vw,40px);letter-spacing:-.02em}
h2{font-size:20px;margin:0 0 4px}.sub{margin:0 0 12px;color:var(--ink2)}section{margin:28px 0}.muted{color:var(--muted);font-size:14px}
.badge{display:inline-flex;align-items:center;gap:8px;padding:5px 12px;border-radius:99px;font-size:13px;font-weight:600;letter-spacing:.04em;background:var(--surface);border:1px solid var(--line)}
.badge .dot{width:9px;height:9px;border-radius:50%;background:var(--good)}.badge.warn .dot{background:var(--warn)}.badge.ghost{font-weight:500;letter-spacing:0;color:var(--ink2)}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.tile{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:14px 16px}
.tile .k{font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)}.tile .v{font-size:22px;font-weight:650;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}
.note{background:var(--surface);border-left:4px solid var(--warn);padding:10px 14px;border-radius:6px}
table{width:100%;border-collapse:collapse;background:var(--surface);border:1px solid var(--line);border-radius:12px;overflow:hidden;margin:10px 0;font-size:14px}
th,td{padding:7px 12px;text-align:left;border-bottom:1px solid var(--line);white-space:nowrap}th{font-size:12px;letter-spacing:.05em;text-transform:uppercase;color:var(--muted);background:var(--bg)}
.r{text-align:right}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px}td.bar{width:34%}td.bar span{display:block;height:8px;border-radius:0 4px 4px 0;background:var(--accent);opacity:.8}
.scroll{overflow-x:auto}.chart{width:100%;height:auto;background:var(--surface);border:1px solid var(--line);border-radius:12px}
.grid{stroke:var(--line)}.axis{fill:var(--muted);font-size:11px}.line{fill:none;stroke-width:2.4;stroke-linejoin:round}.line.inc{stroke:var(--inc)}.line.bound{stroke:var(--bound);stroke-dasharray:6 4}
.pt{stroke:var(--surface);stroke-width:2}.pt.inc{fill:var(--inc)}.pt.bound{fill:var(--bound)}figcaption{margin-top:8px;font-size:14px}.key{display:inline-block;width:18px;height:3px;vertical-align:middle;border-radius:2px}.key.inc{background:var(--inc)}.key.bound{background:var(--bound)}
.tree{background:var(--surface);border:1px solid var(--line);border-radius:12px}.edge{stroke:var(--line);stroke-width:1.5}.edge{stroke:var(--muted);opacity:.45}
.n{stroke:var(--surface);stroke-width:1.5}.n.br{fill:var(--muted)}.n.bd{fill:var(--bound)}.n.fk{fill:var(--bad)}.n.inc{fill:var(--inc)}.n.op{fill:none;stroke:var(--warn);stroke-width:2.5}.n.stub{fill:var(--line);stroke:var(--muted)}.plus{font-size:12px;fill:var(--ink2)}
.legend{display:flex;flex-wrap:wrap;gap:6px 18px;font-size:13px;color:var(--ink2)}.legend svg{vertical-align:middle}
.kv{display:grid;grid-template-columns:max-content 1fr;gap:6px 18px;background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:14px 16px}.kv dt{color:var(--muted)}.kv dd{margin:0;overflow-wrap:anywhere}code{font-family:ui-monospace,Menlo,monospace;font-size:13px}
details{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:10px 16px}summary{cursor:pointer;color:var(--ink2)}pre{overflow:auto;font-size:12.5px;max-height:420px}footer{padding:12px 16px 40px}
@media (max-width:560px){.kv{grid-template-columns:1fr}}
</style></head><body>`
