package viz

const page = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Landmark — __TITLE__</title>
<style>
:root{--bg:#0b0d12;--panel:#12151d;--edge:#232838;--ink:#e8ebf4;--mute:#8a93ab;--acc:#ffb454;--ok:#4be3a1;--bad:#ff6b7a;--blue:#6aa8ff}
*{box-sizing:border-box}
body{margin:0;background:radial-gradient(1200px 600px at 10% -10%,#1a2036 0,transparent 60%),var(--bg);color:var(--ink);
font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
main{max-width:1100px;margin:0 auto;padding:28px 18px 60px}
h1{font-size:13px;letter-spacing:.18em;text-transform:uppercase;color:var(--mute);margin:0 0 14px;font-weight:600}
h1 b{color:var(--acc)}
.verdict{display:flex;flex-wrap:wrap;gap:18px;align-items:center;background:var(--panel);border:1px solid var(--edge);
border-radius:16px;padding:20px 24px;margin-bottom:18px}
.badge{padding:6px 14px;border-radius:999px;font-weight:700;font-size:12px;letter-spacing:.1em}
.badge.ok{background:rgba(75,227,161,.14);color:var(--ok);border:1px solid rgba(75,227,161,.4)}
.badge.no{background:rgba(255,107,122,.12);color:var(--bad);border:1px solid rgba(255,107,122,.4)}
.song{font-size:28px;font-weight:700;letter-spacing:-.01em}
.meta{color:var(--mute);font-size:13px}
.meta b{color:var(--ink);font-weight:600}
.stats{display:flex;gap:26px;margin-left:auto;flex-wrap:wrap}
.stat{min-width:70px}.stat .n{font-size:22px;font-weight:700;font-variant-numeric:tabular-nums}.stat .l{font-size:11px;color:var(--mute);text-transform:uppercase;letter-spacing:.08em}
section{background:var(--panel);border:1px solid var(--edge);border-radius:16px;padding:18px 20px;margin-bottom:18px}
section h2{margin:0 0 4px;font-size:15px}section p{margin:0 0 12px;color:var(--mute);font-size:13px}
canvas{width:100%;display:block;border-radius:10px;background:#05060a}
.row{display:grid;grid-template-columns:1.6fr 1fr;gap:18px}@media(max-width:820px){.row{grid-template-columns:1fr}.stats{margin-left:0}}
.legend{display:flex;gap:16px;flex-wrap:wrap;font-size:12px;color:var(--mute);margin-top:10px;align-items:center}
.dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px;vertical-align:-1px}
label{cursor:pointer;user-select:none}input{accent-color:var(--acc)}
.bars .b{display:grid;grid-template-columns:150px 1fr 70px;gap:10px;align-items:center;margin:7px 0;font-size:13px}
.bars .track{height:12px;background:#0a0c12;border-radius:6px;overflow:hidden;position:relative}
.bars .fill{height:100%;background:var(--blue);border-radius:6px}.bars .b.win .fill{background:var(--ok)}.bars .nm{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.bars .v{text-align:right;font-variant-numeric:tabular-nums;color:var(--mute)}
.note{margin-top:10px;padding:10px 14px;border-radius:10px;background:rgba(255,180,84,.08);border:1px solid rgba(255,180,84,.3);color:#ffd9a3;font-size:13px}
footer{color:var(--mute);font-size:12px;text-align:center;margin-top:26px}
</style></head><body><main>
<h1><b>Landmark</b> · audio fingerprint report · __TITLE__</h1>
<div class="verdict" id="verdict"></div>
<section><h2>Spectrogram, constellation &amp; landmarks</h2>
<p>Each dot is a spectrogram peak that survived non-maximum suppression. Lines are landmarks: an anchor peak paired with a later peak — the (f₁, f₂, Δt) triple that was looked up in the index. <span style="color:var(--ok)">Green</span> landmarks were found in the winning song at the winning alignment.</p>
<canvas id="spec"></canvas>
<div class="legend"><span><span class="dot" style="background:#fff"></span>peak</span>
<span><span class="dot" style="background:var(--ok)"></span>landmark matched in song</span>
<label><input type="checkbox" id="showAll"> show unmatched landmarks</label>
<label><input type="checkbox" id="showPeaks" checked> show peaks</label></div></section>
<div class="row">
<section><h2>Offset histogram</h2><p>Every index collision votes for <i>song time − query time</i>. A real match piles its votes into one spike.</p><canvas id="hist"></canvas></section>
<section><h2>Candidates</h2><p>Aligned votes per song; the amber number after the slash is the strongest rival offset inside that same song (a comb of equal peaks means loops or rhythm-only similarity).</p><div class="bars" id="bars"></div></section>
</div>
<footer>generated by landmark · all numbers computed from the audio, nothing precomputed</footer>
</main>
<script>
const D=__DATA__;
const $=s=>document.getElementById(s);
(function verdict(){
 const v=$('verdict');const ok=D.Found;
 let h='<span class="badge '+(ok?'ok':'no')+'">'+(ok?'MATCH':'NO MATCH')+'</span>';
 if(ok){h+='<div><div class="song">'+esc(D.Song)+'</div><div class="meta">query starts at <b>'+D.OffsetSec.toFixed(2)+' s</b> into the song'+
  (D.Speed!==1?' · playback speed <b>×'+D.Speed.toFixed(3)+'</b>':'')+' · confidence <b>'+Math.round(D.Conf*100)+'%</b></div></div>';}
 else{h+='<div><div class="song" style="font-size:20px">'+esc(D.Reason)+'</div></div>';}
 h+='<div class="stats"><div class="stat"><div class="n">'+D.NPeaks+'</div><div class="l">peaks</div></div>'+
 '<div class="stat"><div class="n">'+D.NHashes+'</div><div class="l">landmarks</div></div>'+
 '<div class="stat"><div class="n">'+D.NMatched+'</div><div class="l">aligned</div></div></div>';
 v.innerHTML=h;
 if(D.Ambiguous&&ok){const n=document.createElement('div');n.className='note';n.style.width='100%';
  n.textContent='This clip lies in repeated material: another offset in the same song also scores highly, so the reported start time may be one of several equally good alignments.';v.appendChild(n);}
})();
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
// inferno-ish colormap
function cmap(u){const s=[[0,0,4],[40,11,84],[101,21,110],[159,42,99],[212,72,66],[245,125,21],[250,193,39],[252,255,164]];
 const x=u*(s.length-1),i=Math.min(s.length-2,Math.floor(x)),f=x-i;return s[i].map((c,k)=>Math.round(c+(s[i+1][k]-c)*f));}
const raw=Uint8Array.from(atob(D.Spec),c=>c.charCodeAt(0));
const spec=$('spec'),sx=spec.getContext('2d');
function drawSpec(){
 const dpr=window.devicePixelRatio||1,W=spec.clientWidth,H=Math.round(Math.max(260,W*.42));
 spec.width=W*dpr;spec.height=H*dpr;spec.style.height=H+'px';sx.setTransform(dpr,0,0,dpr,0,0);
 const off=document.createElement('canvas');off.width=D.Frames;off.height=D.Bins;const ox=off.getContext('2d'),im=ox.createImageData(D.Frames,D.Bins);
 for(let t=0;t<D.Frames;t++)for(let b=0;b<D.Bins;b++){const c=cmap(raw[t*D.Bins+b]/255),y=D.Bins-1-b,o=(y*D.Frames+t)*4;im.data[o]=c[0];im.data[o+1]=c[1];im.data[o+2]=c[2];im.data[o+3]=255;}
 ox.putImageData(im,0,0);sx.imageSmoothingEnabled=true;sx.drawImage(off,0,0,W,H);
 const X=t=>(t+.5)/D.Frames*W,Y=f=>H-(f-D.MinBin+.5)/D.Bins*H;
 const all=$('showAll').checked;
 sx.lineWidth=1;
 if(all){sx.strokeStyle='rgba(138,147,171,.28)';sx.beginPath();for(const p of D.Pairs){if(p.M)continue;sx.moveTo(X(p.A[0]),Y(p.A[1]));sx.lineTo(X(p.B[0]),Y(p.B[1]));}sx.stroke();}
 sx.strokeStyle='rgba(75,227,161,.9)';sx.lineWidth=1.4;sx.beginPath();for(const p of D.Pairs){if(!p.M)continue;sx.moveTo(X(p.A[0]),Y(p.A[1]));sx.lineTo(X(p.B[0]),Y(p.B[1]));}sx.stroke();
 if($('showPeaks').checked){sx.fillStyle='#fff';for(const [t,f] of D.Peaks){sx.beginPath();sx.arc(X(t),Y(f),2,0,6.283);sx.fill();}}
 // axes labels
 sx.fillStyle='rgba(255,255,255,.7)';sx.font='11px system-ui';
 const secs=D.Frames*D.FrameSec;for(let s=0;s<=secs;s+=Math.max(1,Math.round(secs/8))){sx.fillText(s+'s',X(s/D.FrameSec)+3,H-5);}
 for(const hz of [500,1000,2000,3000]){const f=hz/D.BinHz;if(f>D.MinBin&&f<D.MinBin+D.Bins)sx.fillText(hz+' Hz',4,Y(f)-3);}
}
function drawHist(){
 const c=$('hist'),x=c.getContext('2d'),dpr=window.devicePixelRatio||1,W=c.clientWidth,H=240;
 c.width=W*dpr;c.height=H*dpr;c.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,W,H);
 if(!D.Hist.length){x.fillStyle='#8a93ab';x.font='13px system-ui';x.fillText('no collisions',14,28);return;}
 const lo=D.Hist[0][0],hi=D.Hist[D.Hist.length-1][0],span=Math.max(1,hi-lo),max=Math.max(...D.Hist.map(h=>h[1]));
 const pad=26;const X=d=>pad+(d-lo)/span*(W-2*pad),Y=v=>H-24-v/max*(H-44);
 x.strokeStyle='#232838';x.beginPath();x.moveTo(pad,H-24);x.lineTo(W-pad,H-24);x.stroke();
 for(const [d,v] of D.Hist){const hit=Math.abs(d-D.BestDelta)<=1&&D.Found;x.fillStyle=hit?'#4be3a1':'#6aa8ff';x.fillRect(X(d)-1,Y(v),2,H-24-Y(v));}
 x.fillStyle='#8a93ab';x.font='11px system-ui';x.fillText('song time − query time (s)  '+(lo*D.FrameSec).toFixed(0)+' … '+(hi*D.FrameSec).toFixed(0),pad,H-6);
 x.fillStyle='#e8ebf4';x.fillText(max+' votes',pad,12);
}
(function bars(){
 const el=$('bars');const max=Math.max(1,...D.Scores.map(s=>s.Score));
 el.innerHTML=D.Scores.map((s,i)=>'<div class="b'+(i===0&&D.Found?' win':'')+'"><div class="nm" title="'+esc(s.Name)+'">'+esc(s.Name)+'</div><div class="track"><div class="fill" style="width:'+(s.Score/max*100)+'%"></div></div><div class="v">'+s.Score+' <span style="color:var(--acc)">/'+s.Alt+'</span></div></div>').join('')||'<p>No candidates.</p>';
})();
function draw(){drawSpec();drawHist();}
$('showAll').onchange=$('showPeaks').onchange=draw;addEventListener('resize',draw);draw();
</script></body></html>`
